[package]
name = "dpll"
version = "0.1.0"
authors = ["Christian Bild", "Mingzi Kong"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3"